### PR TITLE
Migrate github action to rolling

### PR DESCRIPTION
**Pull request by norro**
* Use latest ros-tooling actions
* Build for rolling
* Migrated launch files to rolling launch API

### CODE REVIEW

**Comment by norro** [comment]
This is in preparation of adding launch tests. @robbel @gbiggs can you have a look? I somehow don't have permissions to request a review.

I guess that we want to create a `foxy` branch from `main` before merging this PR.

**Review by robbel — DISMISSED** [review]

**Comment by robbel** [comment]
Thanks @norro for the contributions, looks good to me.
@gbiggs I created a `foxy` branch so merging this into `main` is fine.

**Comment by gbiggs** [comment]
@norro you need to GPG-sign your commits. Look at the GitHub documentation for how to generate a GPG key and tie it to your account. [This gist](https://gist.github.com/mort3za/ad545d47dd2b54970c102fe39912f305) has the command you need to sign commits you've already made.

**Comment by norro** [comment]
@gbiggs Oh, I see. I thought the weaker `commit -s` was enough. I will do so.

**Comment by gbiggs** [comment]
GPG signing is separate from DCO sign-off.

**Review by robbel — APPROVED** [review]
LGTM!

**Pull request merged**
